version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:1.0.4
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - overchain-network

  mysql:
    image: mysql:5.7
    hostname: mysql
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - overchain-network
    environment: 
      MYSQL_ROOT_PASSWORD: OverChain2022!
      MYSQL_DATABASE: overchain
      MYSQL_USER: root
      MYSQL_PASSWORD: OverChain2022! 
      MYSQL_HOST: localhost
      MYSQL_PORT: 4306

  # app:
  #   build: .
  #   volumes:
  #       - .:/src
  #       - nodemodules:/src/node_modules
  #   restart: on-failure
  #   # command: npm test
  #   ports:
  #       - 3000:3000
  #   links:
  #       - mysql
  #   depends_on: 
  #       - mysql
  #   environment: 
  #     MYSQL_ROOT_PASSWORD: OverChain2022!
  #     MYSQL_DATABASE: overchain
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: OverChain2022! 
  #     MYSQL_HOST: localhost
  #     MYSQL_PORT: '4306'  
  #   networks:
  #     - overchain-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - overchain-network

networks:
  overchain-network:
    driver: bridge