service: tooling-jest-docker-plus
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    LOCALSTACK_HOST: ${env:LOCALSTACK_HOST, "localhost"}
    MYSQL_HOST: ${env:LOCALSTACK_HOST, "localhost"} 
    MYSQL_PORT: ${env:MYSQL_PORT, "4306"}
    MYSQL_USER: ${env:MYSQL_USER, "root"}
    MYSQL_PASSWORD: ${env:MYSQL_PASSWORD, "OverChain2022!"} 
    MYSQL_DATABASE: ${env:MYSQL_DATABASE, "overchain"} 
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:ListAllMyBuckets
          Resource: '*'
plugins:
  - serverless-offline

functions:
  criarCriptomoeda:
    handler: ./src/index.controllers.example.criarCriptomoeda
    events:
      - httpApi:
          path: /
          method: get
